GET http://localhost:8000/api/v1/

###
POST http://localhost:8000/api/v1/auth/
Content-Type: application/json

{
    "name": "Test",
    "password": "pass"
}

###

GET http://localhost:8000/api/v1/users/2

###
